# This is a basic workflow to help you get started with Actions

name: tests

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          - 27.1
          
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Setup Emacs
        uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}
        
      - name: Setup Cask
        uses: conao3/setup-cask@master

      - name: Checkout org-ol-tree repo
        uses: actions/checkout@v2

      - name: Test
        env:
          COVERALLS_FLAG_NAME: Emacs ${{ matrix.emacs_version }}
          COVERALLS_PARALLEL: 1
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cask install
          cask exec buttercup -L . -L tests

  finalize:
    runs-on: ubuntu-latest
    if: always()
    needs: test

    steps:
      - run: curl "https://coveralls.io/webhook?repo_name=$GITHUB_REPOSITORY&repo_token=${{ secrets.GITHUB_TOKEN }}" -d "payload[build_num]=$GITHUB_RUN_NUMBER&payload[status]=done"
