# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          - 26.1
          - 26.2
          - 26.3
          - 27.1
          
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Setup Emacs
        uses: purcell/setup-emacs@v3.0
        with:
          version: ${{ matrix.emacs_version }}
        
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          architecture: 'x64'
        
      - name: Setup Cask
        uses: cask/setup-cask@master
        with:
          version: 'snapshot'
      
      - name: Checkout org-ol-tree repo
        uses: actions/checkout@v2

      - name: Install Cask dependencies
        run: cask install

      - name: Run tests
        run: cask exec buttercup -L . -L tests

      - name: Check coverage with Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
