# This is a basic workflow to help you get started with Actions

name: tests

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          - 27.1
          - 27.2
          
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Setup Emacs
        uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}
        
      - name: Setup Cask
        uses: conao3/setup-cask@master

      - name: Checkout org-ol-tree repo
        uses: actions/checkout@v2

      - name: Test
        env:
          CODECOV_TOKEN: e4cd40cc-11f1-4088-ac9b-5c77a72a50eb
        run: |
          make update
          make test

      - name: Generating code coverage
        uses: actions/upload-artifact@master
        with:
          name: coverage-final.json
          path: ./coverage-final.json

  finalize:
    runs-on: ubuntu-latest
    if: always()
    needs: test

    steps:
      - name: Downloading code coverage data
        uses: actions/download-artifact@master
        with:
          name: coverage-final.json
          path: ./coverage-final.json

      - name: Upload to CodeCov
        env:
          CODECOV_TOKEN: e4cd40cc-11f1-4088-ac9b-5c77a72a50eb
        run: |
          bash <(curl -s https://codecov.io/bash)
